# Generated by Django 5.2.6 on 2025-09-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='edu.field'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='edu.major'),
        ),
    ]
