# Generated by Django 5.2.6 on 2025-09-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_uid_customuser_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verified',
        ),
    ]
