# Generated by Django 5.0.4 on 2024-07-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
