# Generated by Django 5.0.4 on 2024-07-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_uploaded_at_categorymodel_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
