# Generated by Django 5.2.6 on 2025-10-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=b'1', upload_to='posts'),
            preserve_default=False,
        ),
    ]
