# Generated by Django 5.0.4 on 2024-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_categorymodel_options_alter_postmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_category_product', to='blog.postmodel'),
        ),
    ]
