# Generated by Django 5.0.4 on 2024-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorymodel_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='posts',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_category_post', to='blog.postmodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.ManyToManyField(related_name='rel_post_category', to='blog.categorymodel'),
        ),
    ]
