# Generated by Django 5.0.4 on 2024-07-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_categorymodel_options_alter_postmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='post',
        ),
    ]
