# Generated by Django 5.0.4 on 2024-08-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_categorymodel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='is_sub_category',
        ),
    ]
