# Generated by Django 5.0.4 on 2024-08-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_categorymodel_is_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='sub_category',
            new_name='parent_category',
        ),
    ]
