# Generated by Django 5.0.4 on 2024-08-05 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_sub_category_categorymodel_parent_category'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Tag',
        #     fields=[
        #         ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taggit.tag')),
        #     ],
        #     options={
        #         'verbose_name': 'Tag',
        #         'verbose_name_plural': 'Tags',
        #     },
        #     bases=('taggit.tag',),
        # ),
        # migrations.AlterField(
        #     model_name='postmodel',
        #     name='tags',
        #     field=models.ManyToManyField(related_name='rel_post_tags', to='blog.tag'),
        # ),
    ]
