# Generated by Django 5.2.6 on 2025-10-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('degree', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PHD')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('majors', models.ManyToManyField(related_name='fields', to='edu.major')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lesson_name', models.CharField(max_length=250)),
                ('period', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('is_accessible', models.BooleanField(blank=True, default=False, null=True)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='edu.major')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professor-photo/')),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('awards_and_honors', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('fields', models.ManyToManyField(related_name='professors', to='edu.field')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='publication-files/')),
                ('authors', models.ManyToManyField(related_name='publications', through='edu.Authorship', to='edu.professor')),
            ],
        ),
        migrations.AddField(
            model_name='authorship',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.publication'),
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.professor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', through='edu.Teaching', to='edu.professor'),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logo/')),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='universities', to='edu.course')),
                ('majors', models.ManyToManyField(blank=True, null=True, related_name='uiversities', to='edu.major')),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.university'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='edu.major')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='edu.professor')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='edu.university')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('major', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='edu.major')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='edu.professor')),
                ('university', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='edu.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='university_image/')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='edu.university')),
            ],
        ),
    ]
