# Generated by Django 5.2.6 on 2025-09-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='edu.major')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('studylevel', models.CharField(choices=[('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('PHD', 'Phd')], max_length=9)),
                ('period', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('online', models.BooleanField(blank=True)),
                ('on_campus', models.BooleanField(blank=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('major', models.ManyToManyField(blank=True, to='edu.major')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('office_location', models.CharField(max_length=100)),
                ('research_interests', models.TextField()),
                ('publications', models.TextField()),
                ('courses_taught', models.TextField()),
                ('biography', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('education', models.TextField()),
                ('awards_and_honors', models.TextField()),
                ('professional_associations', models.TextField()),
                ('projects', models.TextField()),
                ('rating', models.IntegerField()),
                ('course', models.ManyToManyField(related_name='profcourses+', to='edu.courses')),
                ('major', models.ManyToManyField(to='edu.major')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='professrs',
            field=models.ManyToManyField(blank=True, to='edu.professor'),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
                ('rank', models.PositiveSmallIntegerField()),
                ('scholarships', models.BooleanField()),
                ('images', models.ImageField(upload_to='uni_image')),
                ('price', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, to='edu.courses')),
                ('majors', models.ManyToManyField(blank=True, to='edu.major')),
                ('professors', models.ManyToManyField(blank=True, related_name='working_professors+', to='edu.professor')),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.ManyToManyField(blank=True, to='edu.university'),
        ),
    ]
