# Generated by Django 5.2.6 on 2025-10-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='field',
            name='major',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='courses_taught',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='professional_associations',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='university',
        ),
        migrations.RemoveField(
            model_name='university',
            name='images',
        ),
        migrations.RemoveField(
            model_name='university',
            name='price',
        ),
        migrations.RemoveField(
            model_name='university',
            name='scholarships',
        ),
        migrations.AddField(
            model_name='field',
            name='majors',
            field=models.ManyToManyField(related_name='fields', to='edu.major'),
        ),
        migrations.AddField(
            model_name='major',
            name='degree',
            field=models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PHD')], default='PHD', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='fields',
            field=models.ManyToManyField(related_name='professors', to='edu.field'),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logo/'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='awards_and_honors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='professor-photo/'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='research_interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='majors',
            field=models.ManyToManyField(blank=True, null=True, related_name='uiversities', to='edu.major'),
        ),
        migrations.AlterField(
            model_name='university',
            name='professors',
            field=models.ManyToManyField(blank=True, null=True, related_name='universities', to='edu.professor'),
        ),
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('is_accessible', models.BooleanField(blank=True, default=False, null=True)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='edu.major')),
                ('professors', models.ManyToManyField(blank=True, null=True, related_name='courses', to='edu.professor')),
            ],
        ),
        migrations.AlterField(
            model_name='university',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='universities', to='edu.course'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('major', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='edu.major')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='edu.professor')),
                ('university', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='edu.university')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='edu.major')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='edu.professor')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='edu.university')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='publication-files/')),
                ('authors', models.ManyToManyField(related_name='publications', to='edu.professor')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='university_image/')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='edu.university')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
