# Generated by Django 5.2.6 on 2025-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_remove_professor_course_remove_field_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
