# Generated by Django 5.2.6 on 2025-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_course_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
