# Generated by Django 5.2.6 on 2025-10-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_alter_education_graduation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='professors',
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.university'),
        ),
    ]
