# Generated by Django 5.0.1 on 2024-07-18 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_rename_on_campus_courses_on_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
